### ISSUE TITLE
Adding these tests to WPT?

### ISSUE THREAD

**Issue by astearns** [ccameron-chromium/webgl-examples#1]
Heya - I went looking for test results in wpt.fyi around support for drawingBufferColorSpace and unpackColorSpace, and did not find any. Are there cross-browser tests for wide gamut colors in WebGL in WPT that I missed? If not, would it make sense to submit tests like the examples here?

**Comment by ccameron-chromium** [comment]
Tests for this feature are in Khronos. An initial set (exercising mostly video paths) landed [here](https://github.com/KhronosGroup/WebGL/commit/9361dbfc42dcf4561f8a7e7ac82da32400241d24).

**Comment by ccameron-chromium** [comment]
(Khronos WebGL conformance tests, to be specific)

**Comment by astearns** [comment]
Thanks - I see now that there are issues open in WPT to move their remaining WebGL tests over there, too
